SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `article`;
CREATE TABLE `article` (
  `USERNAME` varchar(8) NOT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTENT` text NOT NULL,
  `PIC` varchar(255) DEFAULT NULL,
  `ADDTIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `EDITTIME` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`USERNAME`) REFERENCES `user` (`USERNAME`)
) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
