SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `comment`;
CREATE TABLE `comment` (
  `FROMUSERNAME` varchar(8) NOT NULL,
  `ID` int(11) NOT NULL,
  `CONTENT` text DEFAULT NULL,
  `ADDTIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `EDITTIME` date DEFAULT NULL,
  FOREIGN KEY (`ID`) REFERENCES `artice` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;