SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `USERNAME` varchar(8) NOT NULL DEFAULT '',
  `PASSWORD` varchar(12) NOT NULL,
  `MAIL` varchar(255) DEFAULT NULL,
  `CODE` varchar(255) DEFAULT NULL,
  `ADDTIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `HEADIMG` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`USERNAME`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


